import React from "react";
import * as sc from "./styles";

const FacturacionMensual = () => {
  return (
    <sc.RotacionesContainer>
      <sc.RotacionTitle>Facturación Mensual</sc.RotacionTitle>
      <sc.GeneralContainer>
        <sc.RotacionesTableContainer>
          <sc.RotacionesGrid>
            <sc.RotacionesTitleItem>
              <p>Octube</p>
              <p>2020</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Noviembre</p>
              <p>2020</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Diciembre</p>
              <p>2020</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Enero</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Febrero</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Marzo</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Abril</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Mayo</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Junio</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Julio</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Agosto</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
            <sc.RotacionesTitleItem>
              <p>Septiembre</p>
              <p>2021</p>
            </sc.RotacionesTitleItem>
          </sc.RotacionesGrid>
          <sc.RotacionesResultsContainer>
            <sc.RotacionesResultsItem>
              <p>5</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>3</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>4</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>7</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>4</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>2</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>1</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>3</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>3</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>4</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>4</p>
            </sc.RotacionesResultsItem>
            <sc.RotacionesResultsItem>
              <p>4</p>
            </sc.RotacionesResultsItem>
          </sc.RotacionesResultsContainer>
        </sc.RotacionesTableContainer>
      </sc.GeneralContainer>
    </sc.RotacionesContainer>
  );
};

export default FacturacionMensual;
